language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  - curl https://raw.githubusercontent.com/AeroNotix/cl-travis/master/install.sh | bash
  - wget http://aphyr.com/riemann/riemann_0.2.7_all.deb
  - sudo dpkg -i riemann_0.2.7_all.deb
  - sudo service riemann start

script: "sbcl --eval '(progn (ql:update-all-dists :prompt nil) (ql:quickload :prove) (ql:quickload :ryeboy))' --quit && make test"
