language: common-lisp

env:
  matrix:
    - LISP=sbcl
#    - LISP=ccl
#    - LISP=clisp

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script: "make test"
